import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';

const root = path.resolve(import.meta.dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');

const configExample = read('config.example.js');
const app = read('src/app.js');
const atlasApp = read('src/atlas-app.js');
const atlasHtml = read('atlas.html');
const atlasEvidence = read('src/atlas-evidence.js');
const atlasCaptureScript = read('execution/capture_atlas_articles.py');
const map = read('src/map.js');
const smoke = read('tests/test.js');
const shareHtml = read('share.html');
const server = read('server/gee_tile_server.mjs');
const cogRenderer = read('execution/render_cog_tile.py');

assert.match(configExample, /IMAGE_PROVIDER:\s*"cog"/, 'config.example.js should default Produced Water to COG imagery');
assert.match(configExample, /COG_TILE_ENDPOINT:\s*"\/api\/cog\/tiles"/, 'config.example.js should document the COG tile endpoint');
assert.match(configExample, /GEE_TILE_ENDPOINT:\s*"\/api\/gee\/tiles"/, 'config.example.js should document the GEE tile endpoint');
assert.match(configExample, /ATLAS_GEE_TILE_ENDPOINT:\s*"\/api\/gee\/tiles"/, 'config.example.js should document the Atlas GEE tile endpoint');
assert.match(configExample, /ATLAS_SENTINEL_CREDIT_GUARD:\s*true/, 'config.example.js should document Atlas Sentinel guard override');
assert.match(configExample, /ATLAS_SENTINEL_LIVE_TILES:\s*false/, 'config.example.js should document Atlas Sentinel live-tile override');
assert.match(configExample, /ATLAS_SENTINEL_MIN_ZOOM:\s*14/, 'config.example.js should document Atlas Sentinel zoom override');
assert.match(configExample, /SENTINEL_WMS_SUPPORTS_SCL:\s*false/, 'config.example.js should keep L1C Sentinel WMS SCL disabled by default');
assert.match(configExample, /ATLAS_WMS_SOURCE:\s*"configured"/, 'config.example.js should document the Atlas WMS source switch');
assert.match(configExample, /ATLAS_VIEWER_INSTANCE_ID:\s*""/, 'config.example.js should document the optional Atlas viewer instance override');
assert.match(atlasApp, /atlas-evidence\.js\?v=4/, 'Atlas app should import the current evidence-pack helper');
assert.match(atlasApp, /renderEvidencePanel/, 'Atlas app should render evidence packs in the info panel');
assert.match(atlasApp, /function linkedinGroundTruthForIndex/, 'Atlas app should derive LinkedIn Ground Truth drafts from selected index metadata');
assert.match(atlasApp, /renderLinkedInGroundTruth\(idx\)/, 'Atlas selection should render LinkedIn Ground Truth guidance for the active index');
assert.match(atlasApp, /navigator\.clipboard\.writeText\(currentLinkedInGroundTruthDraft\)/, 'Atlas LinkedIn guidance should copy the generated draft text');
assert.match(atlasApp, /function setCaptureMode/, 'Atlas app should expose a dedicated LinkedIn screenshot capture mode');
assert.match(atlasApp, /function setCaptureView/, 'Atlas app should expose capture comparison view switching');
assert.match(atlasApp, /function applyCaptureComparison/, 'Atlas capture comparison should use existing overlay presentation state');
assert.match(atlasApp, /function hasCaptureOverlayLayer/, 'Atlas capture mode should detect unavailable overlay layers');
assert.match(atlasApp, /function hasCaptureInterpretationLayer/, 'Atlas capture mode should distinguish true-color context from index interpretation');
assert.match(atlasApp, /GEE context only/, 'Atlas capture mode should label the GEE fallback as context-only');
assert.match(atlasApp, /Switch Sentinel WMS on before Capture/, 'Atlas capture mode should explain that Sentinel WMS is required for Atlas index interpretation');
assert.match(atlasApp, /capture-interpretation-layer/, 'Atlas capture mode should apply a legibility boost class to real index overlays');
assert.match(atlasApp, /function captureInterpretationOpacity/, 'Atlas capture mode should share boosted opacity between live view and PNG export');
assert.match(atlasApp, /const exportOpacity = hasCaptureInterpretationLayer\(\) \? captureInterpretationOpacity\(\) : state\.opacity/, 'Atlas split PNG export should preserve the Sentinel WMS interpretation boost');
assert.match(atlasApp, /capture-overlay-unavailable/, 'Atlas capture mode should expose an unavailable-overlay layout state');
assert.match(atlasApp, /btn\.disabled = disabled/, 'Atlas capture mode should disable unavailable overlay controls');
assert.doesNotMatch(atlasApp, /map\.invalidateSize/, 'Atlas capture mode should not invalidate the map and trigger replacement tiles');
assert.match(atlasApp, /window\.getAtlasCaptureState/, 'Atlas app should expose capture-mode state for browser smoke tests');
assert.match(atlasHtml, /id="info-trust"/, 'Atlas info panel should expose the evidence trust badge');
assert.match(atlasHtml, /id="info-evidence"/, 'Atlas info panel should expose evidence links');
assert.match(atlasHtml, /id="info-linkedin-ground-truth"/, 'Atlas info panel should expose LinkedIn Ground Truth guidance');
assert.match(atlasHtml, /One image\. One observation\. One reason it matters\. One interpretive prompt\./, 'Atlas LinkedIn guidance should teach the weekly post shape');
assert.match(atlasHtml, /id="copy-linkedin-ground-truth"/, 'Atlas LinkedIn guidance should provide a copy draft control');
assert.match(atlasHtml, /id="toggle-capture"/, 'Atlas should expose a capture-mode HUD control');
assert.match(atlasHtml, /id="capture-card"/, 'Atlas should include a dedicated LinkedIn screenshot overlay');
assert.match(atlasHtml, /data-capture-view="context"/, 'Atlas capture card should include a context-only comparison view');
assert.match(atlasHtml, /data-capture-view="overlay"/, 'Atlas capture card should include an overlay comparison view');
assert.match(atlasHtml, /data-capture-view="split"/, 'Atlas capture card should include a split comparison view');
assert.match(atlasHtml, /id="capture-split-slider"/, 'Atlas capture card should expose an adjustable split divider');
assert.match(atlasHtml, /id="capture-status"/, 'Atlas capture card should expose status for unavailable overlay states');
assert.match(atlasHtml, /id="capture-provider-label"/, 'Atlas capture card should show the active interpretation provider state');
assert.match(atlasHtml, /leaflet-layer\.capture-interpretation-layer/, 'Atlas capture CSS should boost real index overlays');
assert.match(atlasHtml, /min-height:\s*44px/, 'Atlas capture controls should have touch-friendly compact targets');
assert.doesNotMatch(atlasHtml, /\.atlas-layout\.capture-mode \.capture-split-labels \{ display: none; \}/, 'Atlas compact capture mode should keep split labels understandable');
assert.match(atlasCaptureScript, /skip_catalog: bool = False/, 'Atlas capture script should thread skip-catalog into metadata lookup');
assert.match(atlasCaptureScript, /status": "skipped"/, 'Atlas capture script should record skipped catalog metadata explicitly');
assert.match(atlasCaptureScript, /skip_catalog=args\.skip_catalog/, 'Atlas capture script should pass the skip-catalog option into capture rendering');
assert.match(atlasEvidence, /getAtlasEvidence/, 'Atlas evidence helper should export evidence generation');
assert.match(atlasEvidence, /getAtlasTrust/, 'Atlas evidence helper should export trust tier generation');
assert.match(atlasEvidence, /countsAsAtlasCitation/, 'Atlas evidence helper should separate cited sources from technical links');
assert.match(atlasEvidence, /countsAsCitation:\s*false/, 'Atlas technical evidence links should be explicitly excluded from citation counts');
assert.match(atlasEvidence, /technical:\s*true/, 'Atlas technical evidence links should be marked separately from cited sources');
assert.match(app, /IMAGE_PROVIDER:\s*'cog'/, 'internal app config should default Produced Water to COG imagery');
assert.match(app, /COG_TILE_ENDPOINT:\s*'\/api\/cog\/tiles'/, 'internal app config should provide a COG endpoint');
assert.match(app, /SENTINEL_CREDIT_GUARD:\s*true/, 'Sentinel credit guard should be enabled by default');
assert.match(app, /SENTINEL_LIVE_TILES:\s*false/, 'Sentinel live tiles should be disarmed by default');
assert.match(app, /SENTINEL_MIN_ZOOM:\s*14/, 'Sentinel WMS should require a precise default zoom');
assert.match(app, /SENTINEL_WMS_SUPPORTS_SCL:\s*false/, 'core app should default its bundled L1C WMS layer to no SCL');
assert.match(app, /toggle-sentinel-live/, 'Settings should expose a Sentinel live tile arm switch');
assert.match(app, /sentinel-min-zoom/, 'Settings should expose a Sentinel minimum zoom control');
assert.match(app, /runtimeImageProviderOverride = 'sentinelhub'/, 'Sentinel toolbar switch should route the session to Sentinel Hub');
assert.match(app, /runtimeImageProviderOverride === 'sentinelhub'[\s\S]*runtimeImageProviderOverride = null/, 'Sentinel toolbar switch should restore the default provider when switched off');
assert.match(app, /function isSentinelOnlyShareMode\(\)/, 'app should detect Sentinel-only share mode');
assert.match(app, /function applySentinelOnlyShareConfig\(config\)/, 'app should have a Sentinel-only share config override');
assert.match(app, /config\.IMAGE_PROVIDER = 'sentinelhub'/, 'share mode should force IMAGE_PROVIDER to Sentinel Hub');
assert.match(app, /config\.ALLOW_SENTINEL_FALLBACK = true/, 'share mode should permit the explicit Sentinel route');
assert.match(app, /config\.SENTINEL_CREDIT_GUARD = true/, 'share mode should keep Sentinel credit guard enabled');
assert.match(app, /config\.SENTINEL_LIVE_TILES = true/, 'share mode should keep Sentinel live tiles armed');
assert.match(app, /sentinelOnlyShareMode: isSentinelOnlyShareMode\(\)/, 'provider state should expose share mode');
assert.match(app, /state\.map\.on\('sentinelratelimit'/, 'app should surface Sentinel Hub rate-limit cooldowns');
assert.match(app, /map-layer-status[\s\S]*muted = screened\/no flag[\s\S]*sparse or blank response can be valid/, 'app should distinguish screened negatives, sparse lenses, and failed tile requests');
assert.match(map, /function getSentinelCreditGuardStatus/, 'map layer factory should check the Sentinel credit guard');
assert.match(map, /adaptEvalscriptForSentinelWms\(finalScript, config\.SENTINEL_WMS_SUPPORTS_SCL === true\)/, 'Sentinel WMS scripts should remove L2A-only SCL unless explicitly supported');
assert.match(map, /getSentinelGuardLayer/, 'Sentinel guard should return a local placeholder layer instead of WMS tiles');
assert.match(map, /state\.map\.fire\('sentinelguard'/, 'Sentinel guard should announce blocked WMS rendering');
assert.match(map, /function getRetryAfterMs/, 'Sentinel WMS loader should honor Retry-After cooldowns');
assert.match(map, /state\.map\.fire\('sentinelratelimit'/, 'Sentinel WMS loader should announce 429 cooldowns');
assert.match(map, /tileSize:\s*512/, 'Sentinel WMS tiles should use larger tiles to reduce request count');
assert.match(map, /maxConcurrent:\s*4/, 'Sentinel WMS tiles should support parallel tile loading');
for (const key of ['tc', 'swir_rgb', 'awei', 'ndre', 'ndmi', 'ndwi', 'ndvi', 'savi', 'bsi', 'ndsi', 'si', 'csi', 'hcai', 'hmri', 'ndoi', 'pwi', 'hpwi', 'pwoi', 'lbi']) {
  assert.match(app, new RegExp(`COG_SUPPORTED_INDEX_KEYS[\\s\\S]*['\"]${key}['\"]`), `COG UI should expose renderer-supported ${key}`);
}
assert.match(app, /const COG_SCREEN_INDEX_KEYS = new Set\(\[[\s\S]*'tc'[\s\S]*'lbi'[\s\S]*'ndwi'[\s\S]*'awei'[\s\S]*'pwi'[\s\S]*'pwoi'[\s\S]*'hpwi'[\s\S]*\]\)/, 'Screen flow should prioritize contextual lenses while retaining negative-result composites');
assert.match(app, /function enforceCogTemporalConstraints\(\)/, 'app should guard temporal controls under COG mode');
assert.match(app, /state\.compareType = 'swipe'/, 'COG mode should fall back to swipe compare instead of diff/cumulative');
assert.match(app, /btnDiff[\s\S]*btnCumulative[\s\S]*btn\.disabled = isCog/, 'COG mode should disable nonfunctional diff/cumulative buttons');
assert.match(app, /getProviderReadyBookmarkIndices\(spill\)/, 'bookmark chips should be filtered by active provider support');
assert.match(app, /const providerReady = isIndexProviderReady\(key\);[\s\S]*btn\.disabled = !providerReady/, 'HUD search should list unsupported provider indexes as disabled references');
assert.match(app, /function getActiveConfig\(\)/, 'app should expose active config resolver');
assert.match(app, /requestedProvider === 'sentinelhub'[\s\S]*merged\.IMAGE_PROVIDER = internalAppConfig\.IMAGE_PROVIDER/, 'app should force the internal provider unless Sentinel fallback is explicitly allowed');
assert.match(app, /sentinelFeatureUnavailable\('AOI history scan'\)/, 'AOI scan should be paused under GEE default');
assert.match(app, /sentinelFeatureUnavailable\('Report generation'\)/, 'report generation should be paused under GEE default');
assert.doesNotMatch(app, /getWMSLayer/, 'app shell should use provider-neutral index layers');
assert.match(map, /export function getImageryProvider/, 'map provider helper should be exported');
assert.match(map, /ALLOW_SENTINEL_FALLBACK !== true[\s\S]*return 'cog'/, 'map provider helper should ignore Sentinel Hub unless fallback is explicit');
assert.match(map, /export function getCOGLayer/, 'map should provide a COG tile layer');
assert.match(map, /\/api\/cog\/tiles/, 'map should route COG tiles to the COG endpoint');
assert.match(map, /Public Sentinel-2 COGs \/ Element84 Earth Search/, 'COG attribution should be visible on tiles');
assert.match(map, /fire\('tileloadfinish', \{ layer: activeIdx \}\)/, 'tile completion events should identify the selected lens');
assert.match(map, /onRemove\(map\)[\s\S]*controller\.abort\(\)/, 'removed COG layers should abort stale in-flight tile requests');
assert.match(map, /getCOGLayer[\s\S]*tileSize:\s*256[\s\S]*zoomOffset:\s*0/, 'COG layers should render smooth 1:1 256px tiles without 2x DOM stretching');
assert.match(map, /getCOGLayer[\s\S]*detectRetina:\s*false[\s\S]*maxConcurrent:\s*6/, 'COG layers should avoid Retina request multiplication and load the active view concurrently');
assert.match(map, /export function getGEELayer/, 'map should provide a GEE tile layer');
assert.match(map, /\/api\/gee\/tiles/, 'map should keep the GEE endpoint available');
assert.match(map, /Google Earth Engine \/ Copernicus Sentinel-2/, 'GEE attribution should be visible on tiles');
assert.match(map, /const RateLimitedTile = L\.TileLayer\.extend/, 'Produced Water GEE tiles should use a fetch-based rate-limited tile layer');
assert.match(map, /maxConcurrent:\s*2/, 'Produced Water GEE tiles should limit concurrent browser fetches');
assert.match(map, /detectRetina:\s*true/, 'Produced Water GEE tiles should request sharper retina tiles on high-DPI displays');
assert.match(atlasApp, /requestedProvider === 'cog' && !cfg\.ATLAS_IMAGE_PROVIDER && !runtimeAtlasImageProviderOverride[\s\S]*\? 'gee'[\s\S]*: requestedProvider/, 'Atlas should normalize global COG default to GEE until Atlas formulas are ported');
assert.match(atlasApp, /runtimeAtlasImageProviderOverride = 'sentinelhub'/, 'Atlas Sentinel HUD switch should route the session to Sentinel Hub');
assert.match(atlasApp, /runtimeAtlasImageProviderOverride === 'sentinelhub'[\s\S]*runtimeAtlasImageProviderOverride = null/, 'Atlas Sentinel HUD switch should restore the default provider when switched off');
assert.match(atlasApp, /ALLOW_SENTINEL_FALLBACK === true/, 'Atlas should keep configured Sentinel fallback locked unless explicitly allowed');
assert.match(atlasApp, /function getAtlasSentinelGuardStatus/, 'Atlas should guard Sentinel WMS by armed state and zoom');
assert.match(atlasApp, /function extractProviderErrorMessage/, 'Atlas should parse provider error bodies for visible tile status');
assert.match(atlasApp, /isQuotaExhausted/, 'Atlas should classify Sentinel Hub quota/credit 403 responses');
assert.match(atlasApp, /atlas-toggle-sentinel-live/, 'Atlas should wire a visible Sentinel live-tile switch');
assert.match(atlasApp, /function resolveAtlasWmsSource/, 'Atlas should resolve configured vs viewer WMS sources');
assert.match(atlasApp, /runtimeAtlasWmsSource/, 'Atlas should allow session-only WMS source switching');
assert.match(atlasApp, /atlas-sentinel-source/, 'Atlas should wire a visible Sentinel WMS source selector');
assert.match(atlasApp, /atlas-sentinel-min-zoom/, 'Atlas should wire a visible Sentinel minimum zoom slider');
assert.match(atlasApp, /toggle-bookmark-focus/, 'Atlas should wire a visible bookmark focus point toggle');
assert.match(atlasApp, /function setBookmarkFocusVisible/, 'Atlas should provide a toggleable bookmark focus layer');
assert.match(atlasApp, /L\.circleMarker/, 'Atlas bookmark focus layer should render vector point markers');
assert.match(atlasApp, /function getRetryAfterMs/, 'Atlas Sentinel WMS loader should honor Retry-After cooldowns');
assert.match(atlasApp, /tileSize:\s*512/, 'Atlas Sentinel WMS tiles should use larger tiles to reduce request count');
assert.match(atlasApp, /maxConcurrent:\s*1/, 'Atlas Sentinel WMS should avoid bursty parallel requests');
assert.match(atlasApp, /setAtlasSentinelWmsCooldown/, 'Atlas Sentinel WMS should maintain rate-limit cooldown state');
assert.match(atlasApp, /function applyGEE/, 'Atlas should provide a GEE tile renderer');
assert.match(atlasApp, /app: 'atlas'/, 'Atlas GEE tiles should identify the Atlas app namespace');
assert.match(atlasApp, /this\._maxConcurrent = options\.maxConcurrent \|\| 2/, 'Atlas GEE tiles should queue fetches instead of bursting all tiles');
assert.match(atlasApp, /detectRetina:\s*true/, 'Atlas GEE tiles should request sharper retina tiles on high-DPI displays');
assert.match(atlasApp, /applyAtlasTiles\(idx, bm\.date\)/, 'Atlas selection should use provider-neutral rendering');
assert.match(atlasApp, /applyWMS\(getDisplayEvalscript\(idx\), date, opts\)/, 'Atlas Sentinel fallback should remain explicit');
assert.match(server, /GEE_MAP_NAME_\$\{safeApp\}_\$\{safeIndex\}/, 'GEE server should support app-scoped map names');
assert.match(server, /@google\/earthengine/, 'GEE server should use the official Earth Engine client');
assert.match(server, /import 'dotenv\/config'/, 'GEE server should load local .env values');
assert.match(server, /COPERNICUS\/S2_SR_HARMONIZED/, 'GEE server should use Sentinel-2 SR Harmonized by default');
assert.match(server, /function buildIndexImage/, 'GEE server should build dynamic index images');
assert.match(server, /getMapId/, 'GEE server should create Earth Engine map IDs dynamically');
assert.match(server, /const tileResponseCache = new Map\(\)/, 'GEE server should cache successful tile byte responses');
assert.match(server, /const inFlightTileResponses = new Map\(\)/, 'GEE server should dedupe simultaneous identical tile requests');
assert.match(server, /TILE_FETCH_MAX_CONCURRENT/, 'GEE server should limit outbound Earth Engine tile fetches');
assert.match(server, /tileResp\.status !== 429/, 'GEE server should retry upstream 429 tile responses');
assert.match(server, /GEE_SINGLE_DATE_LOOKBACK_DAYS/, 'GEE server should expand single-date S2 requests to a lookback window');
assert.match(server, /GEE_SINGLE_DATE_FORWARD_DAYS/, 'GEE server should expand single-date S2 requests to a forward window');
assert.match(server, /const maxcc = Number\(searchParams\.get\('maxcc'\) \|\| 90\)/, 'GEE server should use cloud-tolerant default S2 filtering');
assert.match(server, /Browser API keys alone cannot create Earth Engine maps/, 'GEE server should reject API-key-only setup clearly');
assert.match(server, /\/api\/cog\/tiles\//, 'local server should expose COG tile endpoint');
assert.match(server, /\/api\/cog\/prewarm/, 'local server should expose a COG prewarm endpoint');
for (const key of ['tc', 'swir_rgb', 'awei', 'ndre', 'ndmi', 'ndwi', 'ndvi', 'savi', 'bsi', 'ndsi', 'si', 'csi', 'hcai', 'hmri', 'ndoi', 'pwi', 'hpwi', 'pwoi', 'lbi']) {
  assert.match(server, new RegExp(`COG_SUPPORTED_INDEXES[\\s\\S]*['\"]${key}['\"]`), `COG server should explicitly support ${key}`);
}
assert.match(server, /inFlightCogRenders[\s\S]*entry\.clients[\s\S]*entry\.controller\.abort\(\)/, 'COG server should cancel orphaned Python renders after a client switches lenses');
assert.match(server, /const clearMask = scl\.eq\(4\)[\s\S]*scl\.eq\(7\)/, 'GEE provider should use the clear SCL class allow-list');
assert.match(server, /COG_PREWARM_ON_START/, 'COG server should support startup prewarm for demos');
assert.match(server, /function prewarmCogTargets/, 'COG server should prewarm demo target tiles');
assert.match(server, /execution\/render_cog_tile\.py/, 'local server should delegate COG rendering to deterministic execution script');
assert.match(server, /COG_TILE_CACHE_DIR/, 'local server should cache COG tiles on disk');
assert.match(server, /COG_RENDER_VERSION/, 'COG tile cache keys should include renderer versioning');
assert.match(server, /COG_ITEM_CACHE_DIR/, 'local server should pass an item-selection cache to the COG renderer');
assert.match(cogRenderer, /if index_key not in INDEX_BANDS/, 'COG renderer should reject unsupported index keys deterministically');
assert.match(cogRenderer, /Unsupported COG index/, 'COG renderer should name unsupported index failures clearly');
assert.match(cogRenderer, /item_cache_key/, 'COG renderer should cache STAC item selection across index requests');
assert.match(cogRenderer, /alpha = np\.where\(\(score >= threshold\) & valid, 70 \+ ramp \* 165, 0\)/, 'COG overlays should use graded sparse alpha instead of opaque masks');
assert.match(cogRenderer, /def colorize_screening[\s\S]*neutral = np\.array\(\[35, 43, 54\][\s\S]*candidate = \(score >= threshold\) & valid/, 'experimental COG screens should visibly distinguish analyzed negatives from bright candidates');
for (const key of ['pwi', 'hpwi', 'pwoi', 'lbi']) {
  assert.match(cogRenderer, new RegExp(`if index_key == [\"']${key}[\"'][\\s\\S]*return colorize_screening`), `COG ${key} should use the visible screening display without changing its score`);
}
assert.match(cogRenderer, /CLEAR_SCL_CLASSES = \{4, 5, 6, 7\}/, 'COG provider should reject cloud, shadow, snow, saturated, and dark-feature classes');
assert.match(cogRenderer, /standing_water = ndwi > 0\.30[\s\S]*surface_gate = np\.where\(standing_water, 1\.0/, 'COG LBI should preserve the shipped standing-water bypass');
assert.match(smoke, /urlPath\.startsWith\('\/api\/gee\/tiles\/'\)/, 'browser smoke test should stub local GEE tiles');
assert.match(shareHtml, /index\.html\?share=sentinel-only/, 'share entrypoint should route to Sentinel-only mode');

console.log('Imagery provider contract OK');
