// Source-reviewed event references for Atlas records.
//
// `eventDate` is when the documented incident occurred. `date` is a Sentinel-2
// search-window END DATE and is null wherever the event predates the mission —
// Sentinel-2A reached orbit on 2015-06-23, so no Sentinel-2 scene of an earlier
// event exists at any processing level. Those rows are retained because the
// SITE remains inspectable and the source still documents the event; only the
// event itself is unobservable. `sentinelObservable: "sparse"` marks 2015-2016
// events that fall inside the mission but before the L2A archive was dense.
//
// Consumers MUST NOT treat `date` as an acquisition timestamp (see the registry
// field `bookmarkDateRole`) and MUST handle `date: null`.
export const verifiedBookmarks = {
  bhdfsi: [
    { label: "Montecito debris-flow corridor", date: "2018-01-09", lat: 34.44, lng: -119.63, zoom: 12, note: "Documented Thomas Fire post-fire debris-flow disaster; benchmark for burned-slope runout triage, not a live detection.", sourceLabel: "USGS Montecito data release", sourceUrl: "https://www.usgs.gov/data/debris-flow-inundation-and-damage-data-9-january-2018-montecito-debris-flow-event" },
    { label: "Rat Creek / Dolan Fire washout", date: "2021-01-28", lat: 36.06, lng: -121.59, zoom: 13, note: "Caltrans documented a Dolan Fire burn-scar debris flow that washed out a section of Highway 1.", sourceLabel: "Caltrans Rat Creek release", sourceUrl: "https://dot.ca.gov/news-releases/news-release-2021-004" },
    { label: "Glenwood Canyon Grizzly Creek scar", date: "2021-07-23", lat: 39.56, lng: -107.31, zoom: 12, note: "CDOT and USGS documented repeated debris flows from the Grizzly Creek burn scar in Glenwood Canyon.", sourceLabel: "USGS Glenwood Canyon story map", sourceUrl: "https://www.usgs.gov/programs/landslide-hazards/science/glenwood-canyon-colorado-flooding-and-debris-flows-2021" },
    { label: "Poudre Canyon / Cameron Peak scar", date: "2021-07-20", lat: 40.69, lng: -105.57, zoom: 11, note: "USGS documented flooding and debris flows after storms on the Cameron Peak Fire burn area.", sourceLabel: "USGS Cameron Peak debris flows", sourceUrl: "https://www.usgs.gov/programs/landslide-hazards/science/cameron-peak-colorado-fire-flooding-and-debris-flows-july-20" },
    { label: "Gallinas Canyon post-fire flooding", date: "2022-06-17", lat: 35.63, lng: -105.37, zoom: 11, note: "Hermits Peak/Calf Canyon source area for post-fire flooding and debris-flow screening; context is documented, not inferred by this app.", sourceLabel: "USFS Hermits Peak update", sourceUrl: "https://www.fs.usda.gov/r03/santafe/newsroom/releases/hermits-peak-and-calf-canyon-fires-june-17-2022-daily-update" }
  ],
  peti: [
    { label: "Lake Taihu bloom crisis", eventDate: "2007-05-29", date: null, sentinelObservable: false, lat: 31.40, lng: 120.20, zoom: 9, note: "Large cyanobacteria bloom system tied to a drinking-water crisis; useful for virtual phycocyanin proxy testing.", sourceLabel: "Science review on Lake Taihu bloom", sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4142240/" },
    { label: "Western Lake Erie / Toledo intake", eventDate: "2014-08-02", date: null, sentinelObservable: false, lat: 41.69, lng: -83.37, zoom: 9, note: "Documented microcystin drinking-water crisis; benchmark for cyanobacteria-risk screening language.", sourceLabel: "NASA Lake Erie bloom", sourceUrl: "https://earthobservatory.nasa.gov/images/84125/algae-bloom-on-lake-erie" },
    { label: "Utah Lake harmful bloom", eventDate: "2016-07-15", date: "2016-07-15", sentinelObservable: "sparse", lat: 40.17, lng: -111.78, zoom: 10, note: "Utah Lake was affected by a major harmful algal bloom and recreation closures in 2016.", sourceLabel: "Utah DEQ HAB archive", sourceUrl: "https://deq.utah.gov/water-quality/harmful-algal-blooms-home" },
    { label: "Lake Okeechobee bloom outflow", date: "2018-07-10", lat: 26.95, lng: -80.80, zoom: 9, note: "Documented cyanobacteria bloom and downstream concern context; use for bloom-proxy stress testing.", sourceLabel: "NOAA Florida HAB event tracker", sourceUrl: "https://www.climate.gov/news-features/event-tracker/harmful-algal-blooms-linger-parts-southern-florida-july-and-august-2018" },
    { label: "Detroit Lake / Salem advisory", date: "2018-05-29", lat: 44.72, lng: -122.22, zoom: 11, note: "Oregon issued drinking-water advisories after cyanotoxins affected Salem's source-water context.", sourceLabel: "Oregon Health Authority cyanotoxins", sourceUrl: "https://www.oregon.gov/oha/ph/HealthyEnvironments/DrinkingWater/Operations/Treatment/Pages/algae.aspx" }
  ],
  mppdi: [
    { label: "X-Press Pearl nurdle spill", date: "2021-06-02", lat: 7.07, lng: 79.73, zoom: 10, note: "NOAA incident record notes plastic pellets washing ashore after the Sri Lanka container-ship disaster.", sourceLabel: "NOAA IncidentNews X-Press Pearl", sourceUrl: "https://incidentnews.noaa.gov/incident/10290" },
    { label: "Negombo beach pellet landfall", date: "2021-05-27", lat: 7.21, lng: 79.84, zoom: 12, note: "Sri Lanka shoreline benchmark for pellet/debris visibility; source confirms nurdle contamination, not a Sentinel detection.", sourceLabel: "UNEP X-Press Pearl story", sourceUrl: "https://www.unep.org/news-and-stories/story/oil-acid-plastic-inside-shipping-disaster-gripping-sri-lanka" },
    { label: "Durban Harbor nurdle spill", date: "2017-10-10", lat: -29.88, lng: 31.05, zoom: 12, note: "South African government documented polyethylene nurdle loss from MSC Susanna after a storm in Durban Harbor.", sourceLabel: "South African Government nurdle statement", sourceUrl: "https://www.gov.za/news/media-statements/environmental-affairs-plastic-nurdles-incident-along-kwazulu-natal-coastline" },
    { label: "Motagua River Caribbean outlet", date: "2017-10-01", lat: 15.78, lng: -88.60, zoom: 10, note: "River-borne plastic pollution outlet; use as a floating debris benchmark with sargassum and foam rejection.", sourceLabel: "Guatemala MARN Motagua cleanup", sourceUrl: "https://guatemala.gob.gt/marn-ha-retirado-350-toneladas-de-desechos-del-rio-motagua/" },
    { label: "Hong Kong pellet spill beaches", eventDate: "2012-08-05", date: null, sentinelObservable: false, lat: 22.24, lng: 114.20, zoom: 11, note: "Documented plastic pellet spill after Typhoon Vicente; coastal benchmark for polymer-brightness screening.", sourceLabel: "Hong Kong government pellet incident", sourceUrl: "https://www.info.gov.hk/gia/general/201208/08/P201208080505.htm" }
  ],
  ttapi: [
    { label: "Batagaika megaslump", eventDate: "2016-06-07", date: "2016-06-07", sentinelObservable: "sparse", lat: 67.58, lng: 134.77, zoom: 11, note: "NASA describes Batagaika as a large expanding permafrost thaw slump; benchmark for thaw exposure and wet organic terrain.", sourceLabel: "NASA Batagaika Crater", sourceUrl: "https://earthobservatory.nasa.gov/images/90104/batagaika-crater-expands" },
    { label: "Mackenzie Delta thaw terrain", date: "2019-08-01", lat: 69.35, lng: -134.90, zoom: 9, note: "Arctic delta thaw terrain benchmark; use as a cautious context bookmark for slump and wet-peat proxy testing.", sourceLabel: "NASA Arctic permafrost feature", sourceUrl: "https://earthobservatory.nasa.gov/features/Permafrost" },
    { label: "Banks Island thaw slump field", date: "2017-08-01", lat: 73.00, lng: -121.50, zoom: 8, note: "Well-studied Canadian Arctic retrogressive thaw-slump region; date is a seasonal inspection target.", sourceLabel: "Nature Communications thaw slumps", sourceUrl: "https://www.nature.com/articles/s41467-019-09314-7" },
    { label: "Noatak thaw-slump landscape", date: "2018-08-01", lat: 67.60, lng: -162.60, zoom: 8, note: "Alaska permafrost thaw landscape for testing wet-soil and vegetation-edge collapse behavior.", sourceLabel: "USGS Alaska permafrost science", sourceUrl: "https://www.usgs.gov/centers/alaska-science-center/science/permafrost" },
    { label: "Tuktoyaktuk coastal permafrost", date: "2020-08-01", lat: 69.45, lng: -133.02, zoom: 10, note: "Coastal permafrost and thaw-erosion context; benchmark is location/date context, not methane retrieval.", sourceLabel: "Natural Resources Canada permafrost", sourceUrl: "https://natural-resources.canada.ca/climate-change/climate-change-impacts-forests/permafrost" }
  ],
  ecaci: [
    { label: "Paris heat-island contrast", date: "2019-07-25", lat: 48.86, lng: 2.35, zoom: 11, note: "European heat-wave benchmark for canopy/asphalt contrast; Sentinel-2 is used here for shelter proxy, not air temperature.", sourceLabel: "WMO July 2019 heatwave", sourceUrl: "https://public.wmo.int/en/media/news/july-2019-equalled-and-maybe-surpassed-hottest-month-recorded-history" },
    { label: "Phoenix dry urban grid", date: "2023-07-15", lat: 33.45, lng: -112.07, zoom: 10, note: "Documented extreme urban heat context for comparing shade, imperviousness, and moisture absence.", sourceLabel: "NOAA July 2023 climate report", sourceUrl: "https://www.ncei.noaa.gov/news/national-climate-202307" },
    { label: "Las Vegas heat exposure grid", date: "2021-07-10", lat: 36.17, lng: -115.14, zoom: 10, note: "Urban desert benchmark for dry-surface and tree-canopy contrast under documented heat extremes.", sourceLabel: "NWS Las Vegas climate", sourceUrl: "https://www.weather.gov/vef/climate" },
    { label: "Ahmedabad heat action case", eventDate: "2010-05-21", date: null, sentinelObservable: false, lat: 23.03, lng: 72.58, zoom: 11, note: "Known heat-health city case; bookmark supports microclimate shelter screening, not measured heat.", sourceLabel: "Ahmedabad Heat Action Plan", sourceUrl: "https://www.nrdc.org/resources/ahmedabad-heat-action-plan" },
    { label: "Athens urban heat benchmark", date: "2021-08-03", lat: 37.98, lng: 23.73, zoom: 11, note: "Mediterranean heat-wave city benchmark for canopy/asphalt contrast and shelter absence.", sourceLabel: "WMO Europe heat extremes", sourceUrl: "https://wmo.int/media/news/july-2021-one-of-worlds-hottest-months-record" }
  ],
  lrdvsi: [
    { label: "Belum-Temengor logging edge", date: "2020-03-01", lat: 5.54, lng: 101.35, zoom: 11, note: "Active logging concessions adjacent to royal state park benchmark for buffer-zone intrusion screening.", sourceLabel: "WWF Malaysia Belum-Temengor reports", sourceUrl: "https://www.wwf.org.my/" },
    { label: "Ulu Temburong boundary contrast", date: "2019-07-15", lat: 4.54, lng: 115.16, zoom: 11, note: "Unlogged national park contrasted against neighboring concessions for canopy-gap screening.", sourceLabel: "Brunei Forestry Department national parks", sourceUrl: "http://www.forestry.gov.bn/" },
    { label: "Leuser ecosystem buffer pressure", date: "2022-06-01", lat: 3.40, lng: 97.50, zoom: 10, note: "Sumatran rainforest frontier under logging and agricultural pressure benchmark for road encroachment.", sourceLabel: "HAkA Leuser ecosystem updates", sourceUrl: "https://www.haka.or.id/" },
    { label: "Cardamom Mountains protection edge", date: "2021-12-15", lat: 11.75, lng: 103.25, zoom: 10, note: "Cambodian protected rainforest buffer zone benchmark for canopy gap and dirt road intrusion.", sourceLabel: "Wildlife Alliance Cardamoms protection", sourceUrl: "https://www.wildlifealliance.org/rainforest-protection/" },
    { label: "Sapo National Park buffer encroachment", date: "2020-11-01", lat: 5.35, lng: -8.35, zoom: 10, note: "Liberian rainforest park buffer zone benchmark for canopy disturbance and vigor-slope triage.", sourceLabel: "FDA Liberia Sapo National Park", sourceUrl: "http://www.fda.gov.lr/" }
  ],
  tdrasi: [
    { label: "Rio Tinto acid river", date: "2020-07-01", lat: 37.69, lng: -6.56, zoom: 11, note: "Classic acid-mine-drainage river color benchmark for ferric staining and mineral-water context.", sourceLabel: "NASA Rio Tinto image", sourceUrl: "https://earthobservatory.nasa.gov/images/86319/rio-tinto-spain" },
    { label: "Gold King / Animas River spill", eventDate: "2015-08-05", date: "2015-08-05", sentinelObservable: "sparse", lat: 37.81, lng: -107.66, zoom: 10, note: "EPA-documented mine-water release into Cement Creek and the Animas River; benchmark for orange ferric shock.", sourceLabel: "EPA Gold King Mine response", sourceUrl: "https://www.epa.gov/goldkingmine" },
    { label: "Samarco / Rio Doce tailings runout", eventDate: "2015-11-05", date: "2015-11-05", sentinelObservable: "sparse", lat: -20.20, lng: -43.47, zoom: 9, note: "Documented Fundao tailings failure; benchmark for mineral silt runout and downstream persistence.", sourceLabel: "UNEP Samarco disaster profile", sourceUrl: "https://www.unep.org/news-and-stories/story/brazil-mine-disaster" },
    { label: "Aznalcollar / Guadiamar spill", eventDate: "1998-04-25", date: null, sentinelObservable: false, lat: 37.52, lng: -6.25, zoom: 10, note: "Historic mine-tailings spill near Donana; useful as an acid-silt runout case even though Sentinel-2 did not exist then.", sourceLabel: "European Environment Agency Aznalcollar", sourceUrl: "https://www.eea.europa.eu/publications/92-9167-052-9-sum/page001.html" },
    { label: "Baia Mare cyanide spill", eventDate: "2000-01-30", date: null, sentinelObservable: false, lat: 47.66, lng: 23.58, zoom: 10, note: "Historic mining wastewater disaster; included as a decision-context benchmark, not Sentinel-2 validation imagery.", sourceLabel: "UNEP Baia Mare assessment", sourceUrl: "https://wedocs.unep.org/handle/20.500.11822/8081" }
  ],
  sfeii: [
    { label: "Kahramanmaras earthquake fault trace", date: "2023-02-06", lat: 37.20, lng: 37.00, zoom: 10, note: "Visible surface rupture and massive structural collapse zones across Kahramanmaras and Hatay provinces.", sourceLabel: "USGS M7.8 Turkey Earthquake data release", sourceUrl: "https://www.usgs.gov/news/featured-story/m78-and-m75-earthquakes-turkey-and-syria" },
    { label: "Wenchuan earthquake landslide scarps", eventDate: "2008-05-12", date: null, sentinelObservable: false, lat: 31.00, lng: 103.40, zoom: 10, note: "Hundreds of catastrophic co-seismic landslides stripping mountain vegetation along the fault corridor.", sourceLabel: "USGS Sichuan Earthquake analysis", sourceUrl: "https://earthquake.usgs.gov/earthquakes/eventpage/usp000g650/executive" },
    { label: "Gorkha earthquake debris avalanches", eventDate: "2015-04-25", date: null, sentinelObservable: false, lat: 28.15, lng: 84.70, zoom: 11, note: "Severe structural failures and massive landslides choking steep Himalayan river valleys.", sourceLabel: "USGS Nepal Earthquake data portal", sourceUrl: "https://earthquake.usgs.gov/earthquakes/eventpage/us20002926/executive" },
    { label: "Tohoku co-seismic subsidence zones", eventDate: "2011-03-11", date: null, sentinelObservable: false, lat: 38.30, lng: 141.00, zoom: 9, note: "Massive coastal liquefaction, building collapses, and permanent land subsidence visible along the Sendai coast.", sourceLabel: "USGS Great Tohoku Earthquake reports", sourceUrl: "https://earthquake.usgs.gov/earthquakes/eventpage/official20110311054624120_30/executive" },
    { label: "L'Aquila historic collapse boundary", eventDate: "2009-04-06", date: null, sentinelObservable: false, lat: 42.35, lng: 13.40, zoom: 12, note: "Severe structural damage and masonry collapses throughout the historic center and suburban clay basins.", sourceLabel: "USGS L'Aquila Earthquake catalog", sourceUrl: "https://earthquake.usgs.gov/earthquakes/eventpage/usp000gvgp/executive" }
  ],
  wdacsi: [
    { label: "California Central Valley fallowed fields", date: "2021-07-15", lat: 36.50, lng: -120.20, zoom: 10, note: "Severe drought forcing agricultural fallowing; extreme NDVI decline and MSI crop dehydration signatures.", sourceLabel: "California DWR Drought Portal", sourceUrl: "https://water.ca.gov/water-basics/drought" },
    { label: "Murray-Darling Basin crop stress", date: "2019-01-15", lat: -34.50, lng: 143.50, zoom: 9, note: "Severe agricultural water deficit during the Millennium drought; widespread crop vigor failure.", sourceLabel: "MDBA Drought Monitoring Archive", sourceUrl: "https://www.mdba.gov.au/water-management/drought" },
    { label: "Po Valley agricultural collapse", date: "2022-07-10", lat: 45.20, lng: 10.30, zoom: 10, note: "Worst Italian drought in 70 years; Po River basin crops show severe canopy moisture loss.", sourceLabel: "Copernicus EMS Drought in Europe report", sourceUrl: "https://edo.jrc.ec.europa.eu/edoc/main.php?id=1000" },
    { label: "Sao Paulo sugarcane water deficit", date: "2021-08-20", lat: -21.50, lng: -48.00, zoom: 9, note: "Severe winter drought affecting southeastern Brazil agriculture; high red-edge chlorophyll stress.", sourceLabel: "INMET Brazil Climate Archive", sourceUrl: "https://portal.inmet.gov.br/" },
    { label: "South African maize belt failure", eventDate: "2016-02-10", date: "2016-02-10", sentinelObservable: "sparse", lat: -26.50, lng: 27.00, zoom: 9, note: "Severe El Nino-induced agricultural drought in the Free State; crops show extensive bare soil exposure.", sourceLabel: "South African Weather Service drought reports", sourceUrl: "https://www.weathersa.co.za/" }
  ],
  cduai: [
    { label: "Miami Harbor dredging / reef corridor", eventDate: "2015-05-01", date: null, sentinelObservable: false, lat: 25.75, lng: -80.12, zoom: 11, note: "Documented port-dredging and reef-adjacent sediment concern; benchmark for silt plume rejection gates.", sourceLabel: "NOAA Miami reef injury case", sourceUrl: "https://www.fisheries.noaa.gov/southeast/habitat-conservation/port-miami-deep-dredge-injury-and-restoration" },
    { label: "Princess Charlotte Bay flood plume", eventDate: "2007-02-09", date: null, sentinelObservable: false, lat: -14.30, lng: 144.00, zoom: 9, note: "NASA documented sediment-laden river plumes reaching Great Barrier Reef waters after heavy rains.", sourceLabel: "NASA Great Barrier Reef plumes", sourceUrl: "https://earthobservatory.nasa.gov/images/7537/river-plumes-threaten-great-barrier-reef" },
    { label: "Townsville / Burdekin flood plume", date: "2019-02-10", lat: -18.30, lng: 146.70, zoom: 8, note: "Great Barrier Reef flood-plume context for suspended sediment and coastal water clarity screening.", sourceLabel: "NASA Queensland floods", sourceUrl: "https://earthobservatory.nasa.gov/images/145747/flooding-in-queensland" },
    { label: "Gladstone Harbor dredging context", eventDate: "2011-09-01", date: null, sentinelObservable: false, lat: -23.84, lng: 151.25, zoom: 11, note: "Harbor development and dredging benchmark for nearshore siltation screening; not a reef-health diagnosis.", sourceLabel: "Australian Senate Gladstone report", sourceUrl: "https://www.aph.gov.au/Parliamentary_Business/Committees/Senate/Environment_and_Communications/Completed_inquiries/2010-13/gladstoneharbour/report/index" },
    { label: "Colombo Port City reclamation", eventDate: "2016-09-01", date: "2016-09-01", sentinelObservable: "sparse", lat: 6.93, lng: 79.83, zoom: 12, note: "Large coastal reclamation/dredging setting; benchmark for land, cloud, and plume rejection behavior.", sourceLabel: "Sri Lanka Port City EIA", sourceUrl: "https://www.portcitycolombo.lk/environmental-impact-assessment/" }
  ],
  csrc: [
    { label: "Western Lake Erie Toledo crisis", eventDate: "2014-08-02", date: null, sentinelObservable: false, lat: 41.69, lng: -83.37, zoom: 9, note: "NASA and EPA document microcystin drinking-water impacts; CSRC treats this as scum-risk context only.", sourceLabel: "NASA Lake Erie bloom", sourceUrl: "https://earthobservatory.nasa.gov/images/84125/algae-bloom-on-lake-erie" },
    { label: "Utah Lake 2016 closure", eventDate: "2016-07-15", date: "2016-07-15", sentinelObservable: "sparse", lat: 40.17, lng: -111.78, zoom: 10, note: "Major cyanobacteria public-health closure benchmark for small and medium inland waters.", sourceLabel: "Utah DEQ HAB archive", sourceUrl: "https://deq.utah.gov/water-quality/harmful-algal-blooms-home" },
    { label: "Lake Okeechobee cyanobacteria", date: "2018-07-10", lat: 26.95, lng: -80.80, zoom: 9, note: "Large scum/bloom source-water benchmark with downstream estuary implications.", sourceLabel: "NOAA Florida HAB event tracker", sourceUrl: "https://www.climate.gov/news-features/event-tracker/harmful-algal-blooms-linger-parts-southern-florida-july-and-august-2018" },
    { label: "Clear Lake California HAB", date: "2018-08-01", lat: 39.03, lng: -122.78, zoom: 10, note: "Long-running cyanobacteria/HAB lake benchmark for community health screening.", sourceLabel: "California Water Boards Clear Lake HABs", sourceUrl: "https://www.waterboards.ca.gov/centralvalley/water_issues/swamp/clear_lake_habs/" },
    { label: "Detroit Lake / Salem cyanotoxins", date: "2018-05-29", lat: 44.72, lng: -122.22, zoom: 11, note: "Drinking-water cyanotoxin advisory context; included for public-health scum-risk framing.", sourceLabel: "Oregon Health Authority cyanotoxins", sourceUrl: "https://www.oregon.gov/oha/ph/HealthyEnvironments/DrinkingWater/Operations/Treatment/Pages/algae.aspx" }
  ],
  trsi: [
    { label: "Brumadinho / Paraopeba River", date: "2019-01-25", lat: -20.12, lng: -44.12, zoom: 11, note: "NASA documents tailings rushing toward the Paraopeba River; benchmark for downstream shock screening.", sourceLabel: "NASA Brumadinho dam collapse", sourceUrl: "https://www.earthobservatory.nasa.gov/images/144501/another-deadly-dam-collapse-in-brazil" },
    { label: "Samarco / Rio Doce runout", eventDate: "2015-11-05", date: "2015-11-05", sentinelObservable: "sparse", lat: -20.20, lng: -43.47, zoom: 9, note: "Fundao tailings failure benchmark for sediment shock and persistence in river corridors.", sourceLabel: "UNEP Samarco disaster profile", sourceUrl: "https://www.unep.org/news-and-stories/story/brazil-mine-disaster" },
    { label: "Mount Polley tailings breach", eventDate: "2014-08-04", date: null, sentinelObservable: false, lat: 52.52, lng: -121.63, zoom: 11, note: "British Columbia documents tailings release into Polley Lake and Quesnel Lake watershed.", sourceLabel: "BC Mount Polley response", sourceUrl: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/site-permitting-compliance/mount-polley-mine-incident" },
    { label: "Jagersfontein tailings failure", date: "2022-09-11", lat: -29.76, lng: 25.42, zoom: 11, note: "Documented South African tailings dam failure through settlement drainage; use as a shock benchmark.", sourceLabel: "South Africa parliamentary report", sourceUrl: "https://pmg.org.za/committee-meeting/35611/" },
    { label: "Catoca / Kasai discoloration", date: "2021-07-27", lat: -7.30, lng: 20.85, zoom: 8, note: "Reported mine-related river discoloration benchmark for turbidity/ferric persistence screening.", sourceLabel: "UN OCHA Kasai River update", sourceUrl: "https://reliefweb.int/report/democratic-republic-congo/drc-angola-kasai-river-pollution-flash-update-no-1-13-august-2021" }
  ],
  lfgvi: [
    { label: "Chiquita Canyon Landfill", date: "2024-02-21", lat: 34.44, lng: -118.61, zoom: 12, note: "EPA order documents odor, leachate, and gas/emissions concerns; bookmark is boundary vegetation context.", sourceLabel: "EPA Chiquita Canyon Landfill", sourceUrl: "https://www.epa.gov/ca/chiquita-canyon-landfill" },
    { label: "Bridgeton / West Lake area", eventDate: "2014-09-01", date: null, sentinelObservable: false, lat: 38.78, lng: -90.43, zoom: 12, note: "EPA documents a subsurface smoldering event on the adjacent Bridgeton Landfill side.", sourceLabel: "EPA West Lake fact sheet", sourceUrl: "https://archive.epa.gov/region07/factsheets/web/html/update-westlake-superfund-bridgeton-mo.html" },
    { label: "Sunshine Canyon Landfill", date: "2024-01-01", lat: 34.32, lng: -118.51, zoom: 12, note: "South Coast AQMD documents odor complaints; useful for radial boundary-stress inspection.", sourceLabel: "South Coast AQMD Sunshine Canyon", sourceUrl: "https://www.aqmd.gov/home/news-events/community-investigations/sunshine-canyon-landfill" },
    { label: "Dandora dumpsite school edge", date: "2024-04-01", lat: -1.25, lng: 36.89, zoom: 12, note: "Documented dump-neighborhood interface; benchmark for boundary stress and riparian degradation context.", sourceLabel: "Nairobi Rivers Commission Dandora", sourceUrl: "https://nrc.go.ke/decontamination-dandora-dumpsite" },
    { label: "Kiteezi landfill collapse edge", date: "2024-08-10", lat: 0.40, lng: 32.57, zoom: 12, note: "Uganda Parliament documents the deadly landfill collapse; bookmark is a landfill-boundary risk context, not gas detection.", sourceLabel: "Parliament of Uganda Kiteezi", sourceUrl: "https://www.parliament.go.ug/news/2994/kiteezi-landfill-be-decommissioned-after-tragic-collapse" }
  ],
  swri: [
    { label: "Tijuana River wastewater plume", date: "2024-02-01", lat: 32.55, lng: -117.12, zoom: 11, note: "EPA documents transboundary wastewater and beach-water public-health risks; benchmark for sewage-specific screening.", sourceLabel: "EPA USMCA Tijuana River", sourceUrl: "https://www.epa.gov/sustainable-water-infrastructure/usmca-tijuana-river-watershed" },
    { label: "Tijuana plume from space", date: "2025-06-01", lat: 32.56, lng: -117.14, zoom: 11, note: "NASA reports hyperspectral wastewater-plume mapping; useful truth anchor for sewage-water spectral caution.", sourceLabel: "NASA EMIT Tijuana plume", sourceUrl: "https://www.nasa.gov/missions/station/iss-research/emit/nasa-sensor-on-space-station-eyes-contamination-off-california-coast/" },
    { label: "Buffalo Bayou after Harvey", date: "2017-08-30", lat: 29.76, lng: -95.37, zoom: 11, note: "EPA documented wastewater releases during Harvey flooding; benchmark for urban floodwater sanitation context.", sourceLabel: "EPA Harvey water systems", sourceUrl: "https://www.epa.gov/archive/epa/newsreleases/status-water-systems-areas-affected-harvey.html" },
    { label: "River Thames CSO corridor", date: "2023-09-20", lat: 51.50, lng: -0.12, zoom: 11, note: "Combined-sewer overflow context in a highly monitored urban river; use as discharge-risk screening, not proof of sewage from color alone.", sourceLabel: "Environment Agency spill data", sourceUrl: "https://environment.data.gov.uk/dataset/21e15f12-0df8-4bfc-b763-45226c16a8ac" },
    { label: "Guanabara Bay sewage context", eventDate: "2016-08-05", date: "2016-08-05", sentinelObservable: "sparse", lat: -22.86, lng: -43.15, zoom: 11, note: "Long-documented sewage-pollution setting; benchmark for separating blackwater, turbidity, and ordinary coastal color.", sourceLabel: "Olympics water-quality recognition", sourceUrl: "https://library.olympics.com/digitalCollection/DigitalCollectionAttachmentDownloadHandler.ashx?documentId=158881&parentDocumentId=73418&skipCopyright=true&skipWatermark=true" }
  ],
  dwci: [
    { label: "Paradise / Camp Fire water injury", date: "2018-11-08", lat: 39.76, lng: -121.62, zoom: 10, note: "Documented wildfire water-system contamination context; bookmark supports source-water injury framing.", sourceLabel: "California Water Boards Camp Fire", sourceUrl: "https://www.waterboards.ca.gov/drinking_water/certlic/drinkingwater/CampFire.html" },
    { label: "Cameron Peak source watershed", date: "2020-10-14", lat: 40.61, lng: -105.75, zoom: 10, note: "Post-fire watershed and water-quality context for Fort Collins and Cache la Poudre source areas.", sourceLabel: "Larimer County Cameron Peak watershed", sourceUrl: "https://www.larimer.gov/engineering/cameron-peak-fire-emergency-watershed-program-resiliency-improvements" },
    { label: "Lahaina water-system advisory", date: "2023-08-08", lat: 20.88, lng: -156.68, zoom: 11, note: "Wildfire-damaged community water-system context; use for catchment injury and infrastructure vulnerability screening.", sourceLabel: "Maui County Lahaina water updates", sourceUrl: "https://www.mauicounty.gov/CivicAlerts.aspx?AID=12665" },
    { label: "Bull Run / Eagle Creek Fire watershed", date: "2017-09-02", lat: 45.53, lng: -122.07, zoom: 10, note: "Portland source-water watershed fire context; benchmark for burn scar, turbidity, and treatment-plant concern.", sourceLabel: "Portland Water Bureau Eagle Creek Fire", sourceUrl: "https://www.portland.gov/water/news/2017/9/5/bull-run-watershed-and-eagle-creek-fire" },
    { label: "Las Conchas / Rio Grande source area", eventDate: "2011-06-26", date: null, sentinelObservable: false, lat: 35.83, lng: -106.45, zoom: 10, note: "Large New Mexico wildfire and watershed response context for sediment delivery to drinking-water systems.", sourceLabel: "USGS Las Conchas watershed studies", sourceUrl: "https://www.usgs.gov/centers/new-mexico-water-science-center/science/las-conchas-fire" }
  ],
  rrfi: [
    { label: "Rio Grande / Big Bend low-flow reach", date: "2022-08-01", lat: 29.25, lng: -103.10, zoom: 9, note: "Arid riparian refuge benchmark for drought, channel contraction, and riverbank vegetation stress.", sourceLabel: "National Park Service Rio Grande flows", sourceUrl: "https://www.nps.gov/bibe/learn/nature/rio-grande.htm" },
    { label: "Colorado River Delta restoration reach", eventDate: "2014-05-15", date: null, sentinelObservable: false, lat: 32.20, lng: -115.20, zoom: 9, note: "Managed pulse-flow and riparian restoration context; benchmark for refuge recovery/failure contrast.", sourceLabel: "NASA Colorado River pulse flow", sourceUrl: "https://earthobservatory.nasa.gov/images/83876/a-pulse-of-life-for-the-colorado-river-delta" },
    { label: "Menindee / Darling River fish kill", date: "2019-01-07", lat: -32.40, lng: 142.40, zoom: 9, note: "Australian official investigations documented fish deaths during low-flow, poor-water-quality conditions.", sourceLabel: "NSW Menindee fish deaths", sourceUrl: "https://www.dpi.nsw.gov.au/fishing/habitat/threats/fish-kills/menindee-fish-deaths" },
    { label: "Klamath River drought refuge", eventDate: "2002-09-01", date: null, sentinelObservable: false, lat: 41.85, lng: -123.96, zoom: 9, note: "Documented drought/fish-kill context; use as riparian and channel-refuge stress benchmark.", sourceLabel: "NOAA Klamath salmon disaster", sourceUrl: "https://www.fisheries.noaa.gov/west-coast/endangered-species-conservation/klamath-river-basin" },
    { label: "Lower Murray drought wetlands", date: "2019-02-01", lat: -35.34, lng: 143.56, zoom: 8, note: "Murray-Darling drought and wetland refuge context; bookmark supports hydrology/vegetation stress screening.", sourceLabel: "Murray-Darling Basin Authority drought", sourceUrl: "https://www.mdba.gov.au/water-management/drought" }
  ],
  epdi: [
    { label: "Pajaro River levee breach", date: "2023-03-11", lat: 36.90, lng: -121.75, zoom: 10, note: "Documented flood and levee-breach setting for storm sediment delivery into agricultural waterways.", sourceLabel: "California DWR Pajaro response", sourceUrl: "https://water.ca.gov/News/Blog/2023/Mar-23/Pajaro-Flood-Response" },
    { label: "Vermont July flood erosion", date: "2023-07-11", lat: 44.26, lng: -72.58, zoom: 9, note: "USGS documented flood response context; benchmark for slope erosion and channel sediment delivery.", sourceLabel: "USGS Vermont flood response", sourceUrl: "https://www.usgs.gov/news/state-news-release/usgs-crews-continue-measuring-flooding-vermont" },
    { label: "Indus flood sediment pulse", date: "2022-08-28", lat: 27.70, lng: 68.85, zoom: 8, note: "NASA documented widespread Pakistan flooding along the Indus; use as sediment/floodplain delivery benchmark.", sourceLabel: "NASA Pakistan floods", sourceUrl: "https://earthobservatory.nasa.gov/images/150279/devastating-floods-in-pakistan" },
    { label: "Yellowstone River flood", date: "2022-06-13", lat: 45.02, lng: -110.70, zoom: 9, note: "Documented extreme flood setting for bank erosion, slope connection, and sediment pulse inspection.", sourceLabel: "NASA Yellowstone flooding", sourceUrl: "https://earthobservatory.nasa.gov/images/149937/historic-floods-in-yellowstone" },
    { label: "Colorado Front Range flood", eventDate: "2013-09-12", date: null, sentinelObservable: false, lat: 40.02, lng: -105.28, zoom: 9, note: "Documented flood/erosion event for source-to-channel sediment delivery benchmarking.", sourceLabel: "USGS Colorado flood science", sourceUrl: "https://www.usgs.gov/centers/colorado-water-science-center/science/september-2013-colorado-front-range-flood" }
  ],
  hsai: [
    { label: "Phoenix extreme heat exposure", date: "2023-07-15", lat: 33.45, lng: -112.07, zoom: 10, note: "Documented extreme heat benchmark; HSAI maps shade/moisture absence, not air temperature.", sourceLabel: "NOAA July 2023 climate report", sourceUrl: "https://www.ncei.noaa.gov/news/national-climate-202307" },
    { label: "South Bronx heat inequity", date: "2022-07-20", lat: 40.81, lng: -73.91, zoom: 12, note: "Urban tree-canopy and heat-vulnerability context; benchmark for shelter absence at neighborhood scale.", sourceLabel: "NYC heat vulnerability index", sourceUrl: "https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/climate/?id=2411" },
    { label: "Houston humid heat corridor", date: "2023-08-23", lat: 29.76, lng: -95.36, zoom: 10, note: "Humid heat benchmark where shade and surface moisture matter; avoid thermal-band claims.", sourceLabel: "NOAA August 2023 climate report", sourceUrl: "https://www.ncei.noaa.gov/news/national-climate-202308" },
    { label: "Paris 2019 heatwave", date: "2019-07-25", lat: 48.86, lng: 2.35, zoom: 11, note: "European heat-wave benchmark for shelter absence and urban shade contrast.", sourceLabel: "WMO July 2019 heatwave", sourceUrl: "https://public.wmo.int/en/media/news/july-2019-equalled-and-maybe-surpassed-hottest-month-recorded-history" },
    { label: "Ahmedabad heat-health city", eventDate: "2010-05-21", date: null, sentinelObservable: false, lat: 23.03, lng: 72.58, zoom: 11, note: "Heat action-plan benchmark; use to inspect shade absence and dense impervious exposure.", sourceLabel: "Ahmedabad Heat Action Plan", sourceUrl: "https://www.nrdc.org/resources/ahmedabad-heat-action-plan" }
  ]
};
